import { Song } from "../utils/types";

import img1 from "../assets/images/1.jpg";
import img2 from "../assets/images/2.jpg";
import song1 from "../assets/music/1.mp3";
import song2 from "../assets/music/2.mp3";
import song3 from "../assets/music/3.mp3";
export const PLAYLIST: Song[] = [
  {
    id: "1",
    albumImage: img1,
    songName: "Khawne Gorachand, Khawne Kaalaa",
    artist: "Arijit Singh",
    src: song1,
    duration: "4:13",
  },
  {
    id: "2",
    albumImage: img2,
    songName: "Mon Kyamoner Jonmodin",
    artist: "Mekhla Dasgupta",
    src: song2,
    duration: "4:04",
  },
  {
    id: "3",
    albumImage: img1,
    songName: "Keno Aaj Kal",
    artist: "Nachiketa Chakraborty & Jeet Gannguli",
    src: song3,
    duration: "3:57",
  },
  {
    id: "4",
    albumImage: img1,
    songName: "Songo Chhara Kore Sakhi",
    artist: "Aditi Chakraborty & Ritam Sen",
    src: song1,
    duration: "3:22",
  },
  {
    id: "5",
    albumImage: img1,
    songName: "Bhalobeshe Shokhi",
    artist: "Somlata Acharyya Chowdhury & Arindom",
    src: song1,
    duration: "4:51",
  },
  {
    id: "6",
    albumImage: img1,
    songName: "Hoyto Tomari Janya",
    artist: "Rafiul Islam & Mahmuda",
    src: song1,
    duration: "6:20",
  },
  {
    id: "7",
    albumImage: img1,
    songName: "Ondho Kore Dao",
    artist: "banci",
    src: song1,
    duration: "3:27",
  },
  {
    id: "8",
    albumImage: img1,
    songName: "Hari Haraye Namah Krishna",
    artist: "Padma Palash",
    src: song1,
    duration: "3:51",
  },
  {
    id: "9",
    albumImage: img1,
    songName: "Chirodini Adhare Kete Gelo E Jibon",
    artist: "Ganer Thikana",
    src: song1,
    duration: "3:57",
  },
  {
    id: "10",
    albumImage: img1,
    songName: "Majhe Majhe Tobo Dekha Pai",
    artist: "Mahtim Shakib",
    src: song1,
    duration: "6:12",
  },
  {
    id: "11",
    albumImage: img1,
    songName: "Moloyo Batashe",
    artist: "Sahana Bajpaie",
    src: song1,
    duration: "5:33",
  },
  {
    id: "12",
    albumImage: img1,
    songName: "Rupsagarer Moner Manush",
    artist: "Rishi Panda",
    src: song1,
    duration: "4:48",
  },
  {
    id: "13",
    albumImage: img1,
    songName: "Hey Shokha",
    artist: "Somlata Acharyya Chowdhury & Arindom",
    src: song1,
    duration: "4:24",
  },
  {
    id: "14",
    albumImage: img1,
    songName: "Jodi Boli",
    artist: "Pratik Kundu & Sudeshna Das",
    src: song1,
    duration: "4:06",
  },
  {
    id: "15",
    albumImage: img1,
    songName: "Nithur Monohor",
    artist: "Ishaan",
    src: song1,
    duration: "4:41",
  },
];
